### ISSUE TITLE
not working on ubuntu 20.10

### ISSUE THREAD

**Issue by cprivite** [kvaps/kubectl-node-shell#17]
Looks like it doesn't work on Ubuntu 20.10. If I change the script to use #!/bin/bash instead of #!/bin/sh it works. Otherwise it throws the error:
`/usr/local/cats/bin/kubectl-node_shell: 66: cmd+="bash", "-l" ]: not found`

**Comment by kvaps** [comment]
Hi, dash compatibility was fixed in `v1.2.1`, if you took it from github releases, then sorry I forgot to cut the release on github.

**Comment by kvaps** [comment]
fixed: https://github.com/kvaps/kubectl-node-shell/releases/tag/v1.2.3

**Comment by cprivite** [comment]
Was just able to try the fix and confirmed it works great. Thanks!
