### ISSUE TITLE
Make used image override available

### ISSUE THREAD

**Issue by pietervincken** [kvaps/kubectl-node-shell#19]
Hi all

Since we're in a private cluster, we're unable to directly use the docker.io/alpine image. Currently, that image cannot be overridden in any form. 

Suggestion: add a command line option to override this image.

**Comment by kvaps** [comment]
Makes sense. What do you think about using environment variables?
I guess you would not type the full image name each time when you need to log in into node.

Instead you could use:
```bash
export KUBECTL_NODE_SHELL_IMAGE=your/custom/image:here
```
and add it into your `.bashrc` file

**Comment by pietervincken** [comment]
Thanks, that would work.

**Comment by kvaps** [comment]
Thank you, available in `v1.3.0`
