### ISSUE TITLE
Distribute via krew?

### ISSUE THREAD

**Issue by corneliusweig** [kvaps/kubectl-node-shell#2]
:wave: Hello, maintainer of the kubectl plugin manager [krew](https://github.com/kubernetes-sigs/krew) here.

What do you think about making your plugin available via krew? You would benefit from

- Greater visibility due krew's large user basis.
- Easier installs.
- Seamless upgrades for new plugin versions.

Krew already has over [60 plugins](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md) and more are coming in. See our [development guide](https://github.com/GoogleContainerTools/krew/blob/master/docs/DEVELOPER_GUIDE.md) if you're interested. Please also consult our [naming guide](https://github.com/kubernetes-sigs/krew/blob/master/docs/NAMING_GUIDE.md) to see if your plugin already fulfills our naming requirements.

**Comment by kvaps** [comment]
kubectl-node-shell now part of krew index
