### ISSUE TITLE
How to show gif in README.md?

### ISSUE THREAD

**Issue by laoshanxi** [kvaps/kubectl-node-shell#24]
Dear friend:

I saw you show a very good gif in README, where do you store it and how do you record the gif?

**Comment by kvaps** [comment]
Hi, screen is recoreced using [asciinema.org](https://asciinema.org/) client, and converted to gif using [asciicast2gif](https://github.com/asciinema/asciicast2gif)

The original screencast viedo is accessible here:
https://asciinema.org/a/356519

**Comment by laoshanxi** [comment]
Wow, looks good.

Thanks for sharing, I will also try to use this.
