### ISSUE TITLE
giving error in one one node set but not in other

### ISSUE THREAD

**Issue by ankur8** [kvaps/kubectl-node-shell#43]
}
}' --labels= -t -i nsenter-lwoolh
Error from server (BadRequest): container "nsenter" in pod "nsenter-lwoolh" is not available
+ EC=1
+ kubectl --context=aks-preprod-123-aks-admin --namespace=kube-system delete pod --wait=false nsenter-lwoolh
pod "nsenter-lwoolh" deleted
+ exit 1

**Comment by ankur8** [comment]
working now

**Comment by dragon707** [comment]
> working now

I meet the same problem, how did you solved it.

**Comment by ankur8** [comment]
No its not solved i thought i missed taints

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
