### ISSUE TITLE
kubectl-node-shell 1.7.0 does not support Windows2019

### ISSUE THREAD

**Issue by AbelHu** [kvaps/kubectl-node-shell#46]
`mcr.microsoft.com/powershell` only supports Windows2022 and `kubectl node-shell` will fail with below error with Windows2019.

kubectl-node-shell version: 1.7.0

```
spawning "pwsh-g9mo7u" on "aksnpwin000000"
error: timed out waiting for the condition
pod "pwsh-g9mo7u" deleted
```

kubectl describe po pwsh-g9mo7u:
```
  Warning  Failed   8s    kubelet  Failed to pull image "mcr.microsoft.com/powershell": rpc error: code = NotFound desc = failed to pull and unpack image "mcr.microsoft.com/powershell:latest": no match for platform in manifest: not found
  Normal   BackOff  8s    kubelet  Back-off pulling image "mcr.microsoft.com/powershell"
```

**Comment by AbelHu** [comment]
if using `export KUBECTL_NODE_SHELL_IMAGE_WINDOWS="mcr.microsoft.com/powershell:lts-nanoserver-1809"`, it still fails since   the path in PowerShell 5.1 should be `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe`

**Comment by feiskyer** [comment]
Filed https://github.com/kvaps/kubectl-node-shell/pull/47 to fix this issue
