### ISSUE TITLE
Incorrect Installation Command in README

### ISSUE THREAD

**Issue by Viru9029** [kvaps/kubectl-node-shell#61]
**Title: Incorrect Installation Command in README**

**Description:**

**Issue:**
The installation command provided in the README file is incorrect, causing confusion for users trying to install the plugin using `kubectl krew`.

**Incorrect Command:**
```
kubectl krew install kvaps/node-shell
```

**Correct Command:**
```
kubectl krew install node-shell
```

**Explanation:**
The README suggests installing the `node-shell` plugin using the command `kubectl krew install kvaps/node-shell`. However, this command is incorrect as the plugin is available directly as `node-shell`, not under `kvaps/node-shell`.

**Expected Behavior:**
The README should provide the correct installation command to ensure users can easily install the plugin without encountering errors.

**Steps to Reproduce:**
1. Follow the installation instructions provided in the README.
2. Attempt to install the `node-shell` plugin using the provided command.
3. Observe that the command fails due to the incorrect plugin name.

**Proposed Correction:**
Update the README file with the correct installation command:
```
kubectl krew install node-shell
```
This issue was raised to improve the usability and accuracy of the installation instructions for the project. 
Thank you for your attention to this matter.

**Comment by kvaps** [comment]
This isn't incorrect way for installing, it is just another option.
I just left the comment in similar PR https://github.com/kvaps/kubectl-node-shell/pull/42

**Comment by Viru9029** [comment]
Hi @kvaps 
Can you please tell me how I can do it through 
`kubectl krew install kvaps/node-shell`

**Comment by kvaps** [comment]
The same way as written in readme:

```
kubectl krew index add kvaps https://github.com/kvaps/krew-index
kubectl krew install kvaps/node-shell
```

**Comment by Viru9029** [comment]
But its showing plugin not available.

Additional Query:
I have another question regarding fetching node data. In order to proceed with fetching node data, it's necessary to first authenticate with the IBM Cloud account and execute further commands. However, I've encountered challenges when attempting to perform these actions using bin/bash. Is there a way to install the required login and other commands on the node-shell environment?

**Comment by kvaps** [comment]
I guess this is not part of the plugin logc.

Kubectl node-shell plugin is just replacement for `kubectl run` command

**Comment by Viru9029** [comment]
Hello @kvaps,

We're encountering an issue with IBM nodes within private endpoints. When attempting to execute node-shell commands, we're receiving a "forbidden" error. Could you kindly advise on the specific privilege required to execute these commands successfully? Currently, we have cluster roles and role bindings in place for the nodes, granting permissions for listing, getting, and watching.
