### ISSUE TITLE
KUBECONFIG might overwrite kubectl $KUBECONFIG

### ISSUE THREAD

**Issue by frnksgr** [kvaps/kubectl-node-shell#7]
I use KUBECONFIG env var in context of kubectl to manage arbitrary k8s config files.
(See https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#config)
This can cause kubectl node-shell to fail under certain conditions.

For example:

frank@wdfl30113561a:\~/devel/k8s/cf-for-k8s$ echo $KUBECONFIG                                                                                                                                                                                    /home/frank/.kube/config:/home/frank/devel/k8s/configs/aws-1.yml:/home/frank/devel/k8s/configs/aws-2.yml:/home/frank/devel/k8s/configs/aws-3.yml:/home/frank/devel/k8s/configs/botobot.yml:/home/frank/devel/k8s/configs/gcp-1.yml              

frank@wdfl30113561a:\~/devel/k8s/cf-for-k8s$ kubectl get no                                                                                                                                                                                      NAME                                             STATUS   ROLES    AGE     VERSION                                                                                                                                                              ip-10-250-19-229.eu-central-1.compute.internal   Ready    <none>   3h38m   v1.17.3                                                                                                                                                              ip-10-250-23-109.eu-central-1.compute.internal   Ready    <none>   3h38m   v1.17.3                                                                                                                                                              ip-10-250-3-136.eu-central-1.compute.internal    Ready    <none>   3h38m   v1.17.3                                                                                                                                                              ip-10-250-5-138.eu-central-1.compute.internal    Ready    <none>   3h38m   v1.17.3                                                                                                                                                              

frank@wdfl30113561a:\~/devel/k8s/cf-for-k8s$ kubectl node-shell ip-10-250-19-229.eu-central-1.compute.internal                                                                                                                                   Error in configuration: context was not found for specified context: shoot--frnksgr--aws-1

The error is caused by KUBECONFIG  within kubectl-node_shell  overwriting my environment.

**Comment by kvaps** [comment]
Fixed, thanks for the report!
